M48
; DRILL file {KiCad (6.0.9)} date Mon Mar 20 14:35:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-20T14:35:25+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X4.998Y-2.802
X5.1161Y-2.802
T2
X4.0157Y-2.8504
X5.748Y-2.8504
X5.748Y-4.5827
T0
M30
